[phases.setup]
nixPkgs = ["python313", "gcc"]
# These are the specific Linux 'keys' to unlock OpenCV and YOLO
aptPkgs = ["libgl1", "libglib2.0-0", "libxcb1", "libx11-6"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "reflex run --env prod"
