[phases.setup]
# We added 'libxcb' and 'xorg.libX11' to fix the crash
nixPkgs = ["python313", "gcc", "libglvnd", "glib", "libxcb", "xorg.libX11", "xorg.libXext"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
# The standard production start for a Reflex app.py
cmd = "reflex run --env prod"
